GraphQLError: Minor changes from upstream
Replicates:
- graphql/graphql-js@d8ca570ea9ebd7d5f24b769a0701afea2b001cd7
- graphql/graphql-js@f49cf346e43f9d4fe242bf2d2aa99d2b3fc35b0d
- graphql/graphql-js@6281c06833420c412c7ee41174c8cb1aa7b5cb9a
- graphql/graphql-js@7dc29fd0367e2c9ed3a901c1d809a56edca6b2cf